//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Channel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Channel() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Channel", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 公司地址 的本地化字符串。
        /// </summary>
        internal static string ADDRESS {
            get {
                return ResourceManager.GetString("ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 發票地址 的本地化字符串。
        /// </summary>
        internal static string BILLADDRESS {
            get {
                return ResourceManager.GetString("BILLADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 狀態 的本地化字符串。
        /// </summary>
        internal static string CHANNELSTATUS {
            get {
                return ResourceManager.GetString("CHANNELSTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 該賣場名稱已存在 的本地化字符串。
        /// </summary>
        internal static string CHANNEL_HAS_EXIST {
            get {
                return ResourceManager.GetString("CHANNEL_HAS_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 窗口電子信箱 的本地化字符串。
        /// </summary>
        internal static string CONTACTEMAIL {
            get {
                return ResourceManager.GetString("CONTACTEMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 窗口手機 的本地化字符串。
        /// </summary>
        internal static string CONTACTMOBILE {
            get {
                return ResourceManager.GetString("CONTACTMOBILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 窗口姓名 的本地化字符串。
        /// </summary>
        internal static string CONTACTNAME {
            get {
                return ResourceManager.GetString("CONTACTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 窗口電話1 的本地化字符串。
        /// </summary>
        internal static string CONTACTPHONE1 {
            get {
                return ResourceManager.GetString("CONTACTPHONE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 窗口電話2 的本地化字符串。
        /// </summary>
        internal static string CONTACTPHONE2 {
            get {
                return ResourceManager.GetString("CONTACTPHONE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 窗口屬性 的本地化字符串。
        /// </summary>
        internal static string CONTACTTYPE {
            get {
                return ResourceManager.GetString("CONTACTTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 公司電話 的本地化字符串。
        /// </summary>
        internal static string CONTRACTNUM {
            get {
                return ResourceManager.GetString("CONTRACTNUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 年租費 的本地化字符串。
        /// </summary>
        internal static string COST1 {
            get {
                return ResourceManager.GetString("COST1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 續約年租費 的本地化字符串。
        /// </summary>
        internal static string COST2 {
            get {
                return ResourceManager.GetString("COST2", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 合約結束时间不得早于合約開始时间 的本地化字符串。
        /// </summary>
        internal static string DateTimeEnd {
            get {
                return ResourceManager.GetString("DateTimeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 合約開始时间不得晚于合約結束时间 的本地化字符串。
        /// </summary>
        internal static string DateTimeStart {
            get {
                return ResourceManager.GetString("DateTimeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查詢條件 的本地化字符串。
        /// </summary>
        internal static string DDLSEL {
            get {
                return ResourceManager.GetString("DDLSEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 刪除 的本地化字符串。
        /// </summary>
        internal static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 編輯 的本地化字符串。
        /// </summary>
        internal static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 公司Email 的本地化字符串。
        /// </summary>
        internal static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 ERP客戶代號 的本地化字符串。
        /// </summary>
        internal static string ERPID {
            get {
                return ResourceManager.GetString("ERPID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 操作失败 的本地化字符串。
        /// </summary>
        internal static string FAILED {
            get {
                return ResourceManager.GetString("FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 公司傳真 的本地化字符串。
        /// </summary>
        internal static string FAX {
            get {
                return ResourceManager.GetString("FAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 運費 的本地化字符串。
        /// </summary>
        internal static string FEE {
            get {
                return ResourceManager.GetString("FEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 賣場名稱 的本地化字符串。
        /// </summary>
        internal static string FULLNAME {
            get {
                return ResourceManager.GetString("FULLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 功能 的本地化字符串。
        /// </summary>
        internal static string GONGNENG {
            get {
                return ResourceManager.GetString("GONGNENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 序號 的本地化字符串。
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 匯入模式 的本地化字符串。
        /// </summary>
        internal static string IMPORT {
            get {
                return ResourceManager.GetString("IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新增聯絡人 的本地化字符串。
        /// </summary>
        internal static string INSERTCONTACT {
            get {
                return ResourceManager.GetString("INSERTCONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新增運費 的本地化字符串。
        /// </summary>
        internal static string INSERTSHIPPING {
            get {
                return ResourceManager.GetString("INSERTSHIPPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 會員信箱 的本地化字符串。
        /// </summary>
        internal static string MAILADDRESS {
            get {
                return ResourceManager.GetString("MAILADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 已有賣場使用此會員信箱 的本地化字符串。
        /// </summary>
        internal static string MAIL_WAS_USED {
            get {
                return ResourceManager.GetString("MAIL_WAS_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string MESSAGE {
            get {
                return ResourceManager.GetString("MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 沒有要進行操作的數據 的本地化字符串。
        /// </summary>
        internal static string NO_OPERSTION_DATA {
            get {
                return ResourceManager.GetString("NO_OPERSTION_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 啟用 的本地化字符串。
        /// </summary>
        internal static string ONUSE {
            get {
                return ResourceManager.GetString("ONUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 該貨運物流業者已存在此賣場物流方式 的本地化字符串。
        /// </summary>
        internal static string RECORD_REPEAT {
            get {
                return ResourceManager.GetString("RECORD_REPEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 逆物流運費 的本地化字符串。
        /// </summary>
        internal static string RETURNFEE {
            get {
                return ResourceManager.GetString("RETURNFEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 編號 的本地化字符串。
        /// </summary>
        internal static string ROWNUM {
            get {
                return ResourceManager.GetString("ROWNUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 發票地址同公司地址 的本地化字符串。
        /// </summary>
        internal static string SAMEADDRESS {
            get {
                return ResourceManager.GetString("SAMEADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 合約期間 的本地化字符串。
        /// </summary>
        internal static string SECTION {
            get {
                return ResourceManager.GetString("SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查詢內容 的本地化字符串。
        /// </summary>
        internal static string SELCONTENT {
            get {
                return ResourceManager.GetString("SELCONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 發送通知簡訊(出貨、發票開立) 的本地化字符串。
        /// </summary>
        internal static string SENDMSG {
            get {
                return ResourceManager.GetString("SENDMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 貨運物流業商 的本地化字符串。
        /// </summary>
        internal static string SHIPPINGCAR {
            get {
                return ResourceManager.GetString("SHIPPINGCAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 貨運模式 的本地化字符串。
        /// </summary>
        internal static string SHIPPINGTYPE {
            get {
                return ResourceManager.GetString("SHIPPINGTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 合約簽訂日 的本地化字符串。
        /// </summary>
        internal static string SIGNDATE {
            get {
                return ResourceManager.GetString("SIGNDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 賣場簡稱 的本地化字符串。
        /// </summary>
        internal static string SIMPLENAME {
            get {
                return ResourceManager.GetString("SIMPLENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 操作成功 的本地化字符串。
        /// </summary>
        internal static string SUCCESS {
            get {
                return ResourceManager.GetString("SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 合作賣場 的本地化字符串。
        /// </summary>
        internal static string TEAMWORK {
            get {
                return ResourceManager.GetString("TEAMWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 門檻 的本地化字符串。
        /// </summary>
        internal static string THRESHOLD {
            get {
                return ResourceManager.GetString("THRESHOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 發票抬頭 的本地化字符串。
        /// </summary>
        internal static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 基本資料 的本地化字符串。
        /// </summary>
        internal static string TOP1 {
            get {
                return ResourceManager.GetString("TOP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 聯絡人 的本地化字符串。
        /// </summary>
        internal static string TOP2 {
            get {
                return ResourceManager.GetString("TOP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 運費設定 的本地化字符串。
        /// </summary>
        internal static string TOP3 {
            get {
                return ResourceManager.GetString("TOP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 其他諮詢 的本地化字符串。
        /// </summary>
        internal static string TOP4 {
            get {
                return ResourceManager.GetString("TOP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 賣場類型 的本地化字符串。
        /// </summary>
        internal static string TYPE {
            get {
                return ResourceManager.GetString("TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 禁用 的本地化字符串。
        /// </summary>
        internal static string UNUSE {
            get {
                return ResourceManager.GetString("UNUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 八德路4段768巷7號6樓之1 的本地化字符串。
        /// </summary>
        internal static string USER_ADDRESS {
            get {
                return ResourceManager.GetString("USER_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 公司統編 的本地化字符串。
        /// </summary>
        internal static string WHOLECODE {
            get {
                return ResourceManager.GetString("WHOLECODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 確定刪除 的本地化字符串。
        /// </summary>
        internal static string YDELETE {
            get {
                return ResourceManager.GetString("YDELETE", resourceCulture);
            }
        }
    }
}
