//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChannelOther {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChannelOther() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ChannelOther", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 訂單處理手續費方式 的本地化字符串。
        /// </summary>
        internal static string FIELD1 {
            get {
                return ResourceManager.GetString("FIELD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 成本是否拆分 的本地化字符串。
        /// </summary>
        internal static string FIELD10 {
            get {
                return ResourceManager.GetString("FIELD10", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 賬款區間(每月結帳日) 的本地化字符串。
        /// </summary>
        internal static string FIELD11 {
            get {
                return ResourceManager.GetString("FIELD11", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 每月請款日區間 的本地化字符串。
        /// </summary>
        internal static string FIELD12 {
            get {
                return ResourceManager.GetString("FIELD12", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 結帳請款方式其它說明 的本地化字符串。
        /// </summary>
        internal static string FIELD13 {
            get {
                return ResourceManager.GetString("FIELD13", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 發票開立方式 的本地化字符串。
        /// </summary>
        internal static string FIELD14 {
            get {
                return ResourceManager.GetString("FIELD14", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 管理者 的本地化字符串。
        /// </summary>
        internal static string FIELD15 {
            get {
                return ResourceManager.GetString("FIELD15", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 備註 的本地化字符串。
        /// </summary>
        internal static string FIELD16 {
            get {
                return ResourceManager.GetString("FIELD16", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 無 的本地化字符串。
        /// </summary>
        internal static string FIELD2 {
            get {
                return ResourceManager.GetString("FIELD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 照成交金額%數 的本地化字符串。
        /// </summary>
        internal static string FIELD3 {
            get {
                return ResourceManager.GetString("FIELD3", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 每筆n元 的本地化字符串。
        /// </summary>
        internal static string FIELD4 {
            get {
                return ResourceManager.GetString("FIELD4", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 訂單處理手續費 的本地化字符串。
        /// </summary>
        internal static string FIELD5 {
            get {
                return ResourceManager.GetString("FIELD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 信用卡一期手續費 的本地化字符串。
        /// </summary>
        internal static string FIELD6 {
            get {
                return ResourceManager.GetString("FIELD6", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 信用卡三期手續費 的本地化字符串。
        /// </summary>
        internal static string FIELD7 {
            get {
                return ResourceManager.GetString("FIELD7", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 購物車處理費(每車) 的本地化字符串。
        /// </summary>
        internal static string FIELD8 {
            get {
                return ResourceManager.GetString("FIELD8", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 固定銷售獎勵金(每月%) 的本地化字符串。
        /// </summary>
        internal static string FIELD9 {
            get {
                return ResourceManager.GetString("FIELD9", resourceCulture);
            }
        }
    }
}
