//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Fgroup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Fgroup() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Fgroup", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 人數 的本地化字符串。
        /// </summary>
        internal static string CALLID {
            get {
                return ResourceManager.GetString("CALLID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 群組編碼 的本地化字符串。
        /// </summary>
        internal static string GROUPCODE {
            get {
                return ResourceManager.GetString("GROUPCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 群組名稱 的本地化字符串。
        /// </summary>
        internal static string GROUPNAME {
            get {
                return ResourceManager.GetString("GROUPNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 備註 的本地化字符串。
        /// </summary>
        internal static string REMARK {
            get {
                return ResourceManager.GetString("REMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 重置 的本地化字符串。
        /// </summary>
        internal static string RESET {
            get {
                return ResourceManager.GetString("RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 保存功能模组 的本地化字符串。
        /// </summary>
        internal static string SAVETITLE {
            get {
                return ResourceManager.GetString("SAVETITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 授權失敗 的本地化字符串。
        /// </summary>
        internal static string SET_AUTHORTIY_FAILURE {
            get {
                return ResourceManager.GetString("SET_AUTHORTIY_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 授權成功 的本地化字符串。
        /// </summary>
        internal static string SET_AUTHORTIY_SUCCESS {
            get {
                return ResourceManager.GetString("SET_AUTHORTIY_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 權限分配 的本地化字符串。
        /// </summary>
        internal static string TOOL_AUTHORITY {
            get {
                return ResourceManager.GetString("TOOL_AUTHORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 人員管理 的本地化字符串。
        /// </summary>
        internal static string TOOL_CALLID {
            get {
                return ResourceManager.GetString("TOOL_CALLID", resourceCulture);
            }
        }
    }
}
