//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OrderAdd {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderAdd() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.OrderAdd", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 可使用購物金的金額不足！請確認后再輸入~ 的本地化字符串。
        /// </summary>
        internal static string BONUS_PRICE_NULL {
            get {
                return ResourceManager.GetString("BONUS_PRICE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任選之組成商品需為無規格 的本地化字符串。
        /// </summary>
        internal static string COMBO_CHILD_NO_SPEC {
            get {
                return ResourceManager.GetString("COMBO_CHILD_NO_SPEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此組合商品下的單一商品價格數據不完整，請重新選擇商品。 的本地化字符串。
        /// </summary>
        internal static string COMBO_CHILD_PRICE_NULL {
            get {
                return ResourceManager.GetString("COMBO_CHILD_PRICE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 庫存不足,無法生成訂單 的本地化字符串。
        /// </summary>
        internal static string EMPTY_NULL_FAIL {
            get {
                return ResourceManager.GetString("EMPTY_NULL_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 備註 的本地化字符串。
        /// </summary>
        internal static string NOTE {
            get {
                return ResourceManager.GetString("NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}於{1}建立   {2} 的本地化字符串。
        /// </summary>
        internal static string NOTE_CONTENT {
            get {
                return ResourceManager.GetString("NOTE_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 訂單生成失敗 的本地化字符串。
        /// </summary>
        internal static string ORDER_ADD_FAIL {
            get {
                return ResourceManager.GetString("ORDER_ADD_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 訂單生成成功 的本地化字符串。
        /// </summary>
        internal static string ORDER_ADD_SUCCESS {
            get {
                return ResourceManager.GetString("ORDER_ADD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品未上架 的本地化字符串。
        /// </summary>
        internal static string PRODUCT_DOWN {
            get {
                return ResourceManager.GetString("PRODUCT_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品不存在 的本地化字符串。
        /// </summary>
        internal static string PRODUCT_NOT_EXIST {
            get {
                return ResourceManager.GetString("PRODUCT_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 該商品不能生成訂單 的本地化字符串。
        /// </summary>
        internal static string PRODUCT_NOT_USE_IN_ORDER {
            get {
                return ResourceManager.GetString("PRODUCT_NOT_USE_IN_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品價格不存在 的本地化字符串。
        /// </summary>
        internal static string PRODUCT_PRICE_NOT_EXIST {
            get {
                return ResourceManager.GetString("PRODUCT_PRICE_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 補貨中不能販賣 的本地化字符串。
        /// </summary>
        internal static string SHPRT_AGE {
            get {
                return ResourceManager.GetString("SHPRT_AGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此單一商品規格價格數據錯誤，請重新選擇。 的本地化字符串。
        /// </summary>
        internal static string SINGLE_SPEC_PRICE_WRONG {
            get {
                return ResourceManager.GetString("SINGLE_SPEC_PRICE_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可使用抵用券的金額不足！請確認后再輸入~ 的本地化字符串。
        /// </summary>
        internal static string WELFARE_PRICE_NULL {
            get {
                return ResourceManager.GetString("WELFARE_PRICE_NULL", resourceCulture);
            }
        }
    }
}
