//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OrderImport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderImport() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.OrderImport", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 訂購數量格式錯誤 的本地化字符串。
        /// </summary>
        internal static string BUY_COUNT_WRONG {
            get {
                return ResourceManager.GetString("BUY_COUNT_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 訂購日/付款時間格式錯誤 的本地化字符串。
        /// </summary>
        internal static string BUY_DATE_WRONG {
            get {
                return ResourceManager.GetString("BUY_DATE_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外站訂單編號格式錯誤 的本地化字符串。
        /// </summary>
        internal static string CHANNEL_ORDERID_WRONG {
            get {
                return ResourceManager.GetString("CHANNEL_ORDERID_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外站商品編號格式錯誤 的本地化字符串。
        /// </summary>
        internal static string CHANNEL_PRODUCTID_WRONG {
            get {
                return ResourceManager.GetString("CHANNEL_PRODUCTID_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物流信息未找到對照 的本地化字符串。
        /// </summary>
        internal static string DELIVERY_MAP_NOT_EXISTS {
            get {
                return ResourceManager.GetString("DELIVERY_MAP_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件人郵遞區號格式錯誤 的本地化字符串。
        /// </summary>
        internal static string DELIVERY_ZIP_WRONG {
            get {
                return ResourceManager.GetString("DELIVERY_ZIP_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 庫存不足 的本地化字符串。
        /// </summary>
        internal static string EMPTY_STOCK {
            get {
                return ResourceManager.GetString("EMPTY_STOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匯入成功 的本地化字符串。
        /// </summary>
        internal static string IMPORT_SUCCESS {
            get {
                return ResourceManager.GetString("IMPORT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品細項編號不存在 的本地化字符串。
        /// </summary>
        internal static string ITEMID_ID_NOT_EXISTS {
            get {
                return ResourceManager.GetString("ITEMID_ID_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最晚出貨日格式錯誤 的本地化字符串。
        /// </summary>
        internal static string LAST_DELIVERY_DATE {
            get {
                return ResourceManager.GetString("LAST_DELIVERY_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 訂單已存在 的本地化字符串。
        /// </summary>
        internal static string ORDER_EXISTS {
            get {
                return ResourceManager.GetString("ORDER_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品編號格式錯誤 的本地化字符串。
        /// </summary>
        internal static string PRODUCTID_WRONG {
            get {
                return ResourceManager.GetString("PRODUCTID_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品對照資料不存在 的本地化字符串。
        /// </summary>
        internal static string PRODUCT_MAP_NOT_EXISTS {
            get {
                return ResourceManager.GetString("PRODUCT_MAP_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品不存在 的本地化字符串。
        /// </summary>
        internal static string PRODUCT_NOT_EXISTS {
            get {
                return ResourceManager.GetString("PRODUCT_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 該商品不能生成訂單 的本地化字符串。
        /// </summary>
        internal static string PRODUCT_NOT_USE_IN_ORDER {
            get {
                return ResourceManager.GetString("PRODUCT_NOT_USE_IN_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品價格不存在 的本地化字符串。
        /// </summary>
        internal static string PRODUCT_PRICE_NOT_EXISTS {
            get {
                return ResourceManager.GetString("PRODUCT_PRICE_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品不為上架狀態 的本地化字符串。
        /// </summary>
        internal static string PRODUCT_STATUS_WRONG {
            get {
                return ResourceManager.GetString("PRODUCT_STATUS_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品未處於上架時間內 的本地化字符串。
        /// </summary>
        internal static string PRODUCT_TIME_OUT {
            get {
                return ResourceManager.GetString("PRODUCT_TIME_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        internal static string PRODUCT_WARNING {
            get {
                return ResourceManager.GetString("PRODUCT_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寫入數據庫錯誤 的本地化字符串。
        /// </summary>
        internal static string SAVE_TO_DB_FAILURE {
            get {
                return ResourceManager.GetString("SAVE_TO_DB_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 補貨中不可販賣 的本地化字符串。
        /// </summary>
        internal static string SHORT_AGE {
            get {
                return ResourceManager.GetString("SHORT_AGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金額小計與總金額不符 的本地化字符串。
        /// </summary>
        internal static string SUM_WRONG {
            get {
                return ResourceManager.GetString("SUM_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不可配送 的本地化字符串。
        /// </summary>
        internal static string UNDISPATCHING {
            get {
                return ResourceManager.GetString("UNDISPATCHING", resourceCulture);
            }
        }
    }
}
