//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProductItemMap {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductItemMap() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ProductItemMap", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 組合中之數量(0為照組合中之設定) 的本地化字符串。
        /// </summary>
        internal static string COMBO_NUM_SET {
            get {
                return ResourceManager.GetString("COMBO_NUM_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品對照已存在 的本地化字符串。
        /// </summary>
        internal static string COMPARE_EXISTS {
            get {
                return ResourceManager.GetString("COMPARE_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刪除成功 的本地化字符串。
        /// </summary>
        internal static string DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 庫存不足 的本地化字符串。
        /// </summary>
        internal static string EMPTY_STOCK {
            get {
                return ResourceManager.GetString("EMPTY_STOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式不正確 的本地化字符串。
        /// </summary>
        internal static string ERROR_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您上传的文件有误，请上传Excel格式的文件！ 的本地化字符串。
        /// </summary>
        internal static string EXCEL_FORMAT_ERROR {
            get {
                return ResourceManager.GetString("EXCEL_FORMAT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件表頭無法識別 的本地化字符串。
        /// </summary>
        internal static string EXCEL_HEADER_ERROR {
            get {
                return ResourceManager.GetString("EXCEL_HEADER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失敗!此編號已存在訂單 的本地化字符串。
        /// </summary>
        internal static string EXIST_DELETE_FAIL {
            get {
                return ResourceManager.GetString("EXIST_DELETE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匯出錯誤,請聯繫開發人員! 的本地化字符串。
        /// </summary>
        internal static string EXPORT_ERROR {
            get {
                return ResourceManager.GetString("EXPORT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匯入失敗 的本地化字符串。
        /// </summary>
        internal static string IMPORT_FAIL {
            get {
                return ResourceManager.GetString("IMPORT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匯入成功 的本地化字符串。
        /// </summary>
        internal static string IMPORT_SUCCESS {
            get {
                return ResourceManager.GetString("IMPORT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功匯入{0}條 的本地化字符串。
        /// </summary>
        internal static string IMPORT_SUCCESS_TOTAL {
            get {
                return ResourceManager.GetString("IMPORT_SUCCESS_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品組合不符合 的本地化字符串。
        /// </summary>
        internal static string ITEMID_ID_NOT_COMBINATION {
            get {
                return ResourceManager.GetString("ITEMID_ID_NOT_COMBINATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品細項編號不存在 的本地化字符串。
        /// </summary>
        internal static string ITEMID_ID_NOT_EXISTS {
            get {
                return ResourceManager.GetString("ITEMID_ID_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品細項編號(6碼) 的本地化字符串。
        /// </summary>
        internal static string ITEM_ID {
            get {
                return ResourceManager.GetString("ITEM_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手動建立 的本地化字符串。
        /// </summary>
        internal static string MANUAL_OPERATING {
            get {
                return ResourceManager.GetString("MANUAL_OPERATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外站商品成本 的本地化字符串。
        /// </summary>
        internal static string OUTSITE_PRODUCT_COST {
            get {
                return ResourceManager.GetString("OUTSITE_PRODUCT_COST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外站商品編號 的本地化字符串。
        /// </summary>
        internal static string OUTSITE_PRODUCT_ID {
            get {
                return ResourceManager.GetString("OUTSITE_PRODUCT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外站商品名稱 的本地化字符串。
        /// </summary>
        internal static string OUTSITE_PRODUCT_NAME {
            get {
                return ResourceManager.GetString("OUTSITE_PRODUCT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外站商品售價 的本地化字符串。
        /// </summary>
        internal static string OUTSITE_PRODUCT_PRICE {
            get {
                return ResourceManager.GetString("OUTSITE_PRODUCT_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 會員等級 的本地化字符串。
        /// </summary>
        internal static string PIRCE_USER_LEVEL {
            get {
                return ResourceManager.GetString("PIRCE_USER_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 站臺ID 的本地化字符串。
        /// </summary>
        internal static string PRICE_SITE {
            get {
                return ResourceManager.GetString("PRICE_SITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 會員郵箱 的本地化字符串。
        /// </summary>
        internal static string PRICE_USER_EMAIL {
            get {
                return ResourceManager.GetString("PRICE_USER_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品編號(5碼) 的本地化字符串。
        /// </summary>
        internal static string PRODUCT_ID {
            get {
                return ResourceManager.GetString("PRODUCT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 該商品不存在 的本地化字符串。
        /// </summary>
        internal static string PRODUCT_NOT_EXIST {
            get {
                return ResourceManager.GetString("PRODUCT_NOT_EXIST", resourceCulture);
            }
        }
    }
}
